version: '3.9'

volumes:
  snippets:
    external: true
    name: ${SNIPPETS_DIR}

services:
  proxmanager:
    container_name: proxmanager
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/data
      - "$SNIPPETS_DIR:/snippets"
    ports:
      - "6999:6999"
    tty: true
    environment:
      - TZ=America/Detroit
      - ENV
      - API_TOKEN
